repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest before commit
        entry: pytest tests/
        language: system
        pass_filenames: false
        types: [python]
